// src/components/App.jsx
import { h, Fragment } from 'preact';
import { Router } from 'preact-router';
import { Link } from 'preact-router/match';

import About from './About';
import Home from './Home';
import Registry from './Registry';
import Rsvp from './Rsvp';

const App = () => {
  return (
    <>
      <div className="title">Tying The Knot</div>
      <nav className="navi">
        <div className="vertical-links">
          <Link activeClassName="active" href="/en">
            Home
          </Link>
          <Link activeClassName="active" href="/vn">
            Chính
          </Link>
        </div>
        <div className="vertical-links">
          <Link activeClassName="active" href="/en/about">
            Love Story
          </Link>
          <Link activeClassName="active" href="/vn/about">
            Chuyện
          </Link>
        </div>
        <div className="vertical-links">
          <Link activeClassName="active" href="/en/rsvp">
            RSVP
          </Link>
          <Link activeClassName="active" href="/vn/rsvp">
            Trả-Lời
          </Link>
        </div>
        <div className="vertical-links">
          <Link activeClassName="active" href="/en/registry">
            Registry
          </Link>
          <Link activeClassName="active" href="/vn/registry">
            Tình-Nguyện
          </Link>
        </div>
      </nav>
      <Router>
        <Home path="/:lang?" />
        <About path="/:lang/about" />
        <Rsvp path="/:lang/rsvp" />
        <Registry path="/:lang/registry" />
      </Router>
      <footer id="footer" className="page-footer font-small red">
        <div className="footer-copyright py-3">
          © 2020 Copyright:
          <a href="https://mdbootstrap.com/education/bootstrap/"> Michael and Sophie</a>
        </div>
      </footer>
    </>
  );
};

export default App;

// src/App.vue
<template>
  <div id="app">
    <div class="title"> Tying The Knot </div>
    <nav class="navi">
      <router-link to="/">Home</router-link>
      <router-link to="/about">Love-Story</router-link>
      <router-link to="/rsvp">RSVP</router-link>
      <router-link to="/registry">Registry</router-link>
    </nav>
    <p>________________________________________________</p>
    <nav class="navi">
      <router-link to="/">Chính</router-link>
      <router-link to="/about">Chuyện</router-link>
      <router-link to="/rsvp">Trả-Lời</router-link>
      <router-link to="/registry">Tình-Nguyện</router-link>
    </nav>
    <router-view />
    <!-- Footer -->

    <footer id="footer" class="page-footer font-small red">
      <div class="footer-copyright py-3">© 2020 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/"> Michael and Sophie</a>
      </div>
    </footer>
  </div>
</template>

<script>
  
  import { mdbFooter, mdbContainer, mdbRow, mdbCol } from 'mdbvue';
  export default {
    name: 'FooterPage',
    components: {
      mdbFooter,
      mdbContainer,
      mdbRow,
      mdbCol
    }
  }

</script>

<style type="text/css">
.title {
  font-family:"Morice Straight W03 Bold" !important;
  font-size:150px;font-style:normal;
  -webkit-font-smoothing: antialiased;
  -webkit-text-stroke-width: 1.5px;
  -moz-osx-font-smoothing: grayscale;
  color: red;
  text-align: center;
  margin-bottom: 40px;
}
.navi {
  color: black;
  font-family: "Lucida Sans Unicode", Monaco;
  font-size: 22px;
  letter-spacing: 18px;
  margin-top: 5px;
  text-align: center;
}
.navi a {
  text-decoration: none;
  color: black;
}
.navi a:hover {
  background-color: rgba(255, 204, 204, 0.25);
  color: palevioletred;
}

footer {
  position:fixed;
  bottom:0;
  width:100%;
  height:50px;
  text-align: center;
}

</style>
